## Worksheet 1: Numpy and Matplotlib

This is a _Jupyter notebook_. It consists of a series of _cells_. Some contain simple text, like this one, and some contain code, like the one below. Read each cell carefully. If it contains code, you can click the "play" button above to execute it. Don't execute a new cell until all previous ones have finished executing.

**NB: If you go back up an re-run a cell, it can happen that it doesn't work anymore, because the variable names have been re-used. If something doesn't work, for any reason, please try "Kernel > Restart & Clear Output" and start again from the top. If the error keeps happening, please post a question on the Canvas message board.**

We will assume that you know the basics of Python. If you don't, please work your way through [this tutorial](https://www.learnpython.org/) first to get caught up.

The next cell imports the library **numpy** (short for **num**eric **py**thon).

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks/Machine Learning/Introducción')

In [ ]:
%cd '/content/drive/MyDrive/Colab Notebooks/Machine Learning/Introducción'

/content/drive/MyDrive/Colab Notebooks/Machine Learning/Introducción


In [ ]:
import numpy as np

If you see something like "In [1]:" next to the cell above, execution has finished.

## Numpy

Numpy is a _Linear Algebra_ library. It allows you to represent vectors, matrices and tensors as Python objects, and to manipulate these in all the ways you'd expect. 

Most machine learning research uses Linear Algebra as its basic language, so most machine learning _code_ is built on libraries like numpy.

Let's start by making a 2 x 2 matrix, filled with some arbitrary numbers.

In [ ]:
np.asarray([[2, 3],[4, 5]])

array([[2, 3],
       [4, 5]])

The numpy [documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.asarray.html) can tell you more about all of the functions you see here. Each function is annotated with several examples.

We can also create a matrix of random numbers between 0.0 and 1.0:

In [ ]:
np.random.rand(2,2)

array([[0.93104999, 0.14237097],
       [0.47952779, 0.26588282]])

Note that the numbers change if you execute the cell again. The arguments indicate the _shape_ of the resulting matrix. Try changing the cell above; if you pass rand a single argument, you get a vector. If you pass it more than two arguments, you get a _tensor_ (the higher-dimensional analogue of a matrix).

Let's take a slightly bigger matrix, and see what we can do with it. This time, we'll load some actual data:

In [ ]:
data = np.loadtxt('cricketers.sub.csv', delimiter=',')
print(data)

[[1890.  102.]
 [1892.  100.]
 [1893.   99.]
 ...
 [1876.   88.]
 [1850.   65.]
 [1885.   32.]]


Each row in this matrix represents a professional cricketer from the 19th or 20th century. The first column indicates their year of birth, the second indicates how old they were when the data was collected if they were still alive, or at what age they died, otherwise. 

Let's start by seeing how many cricketers we have:

In [ ]:
data.shape

Our data has 5960 rows, and two columns. We can ask for a specific element of the matrix by using square brackets to index the matrix. Here is the date of birth and age of the 10th cricketer:

In [ ]:
print('year of birth ', data[9, 0])
print('age ', data[9, 1])

**Note that indexing starts from 0.** The first column is column 0, and the second is column 1.

The [slicing syntax](https://www.oreilly.com/learning/how-do-i-use-the-slice-notation-in-python) that you know from python lists can also be used for matrices. For instance, here are the first ten cricketers' years of birth:

In [ ]:
data[0:10, 0]

To check that you understand, see if you can predict the result of the following slicing operations (and then execute the cells):

In [ ]:
data[:10, 1]

In [ ]:
data[0:10, :]

In [ ]:
data[-1, :]

## Matplotlib

The first rule of data science is _look at your data_. We can do this easily with the library **matplotlib**. Let's start by importing it.

In [ ]:
import matplotlib.pyplot as plt
# ensure that plots are displayed inside the notebook
%matplotlib inline 

We've imported the pyplot sublibrary. This library acts as a "state machine", it assumes we are working on a single plot and every command we give changes the state of that plot. This is great for simple plots.

For more complicated stuff, you may want to use [the object-oriented interface](https://matplotlib.org/faq/usage_faq.html). This is a little more complicated, but more powerful.

For now, we can keep things simple. We want a scatter plot of the first column in the data (year of birth) against the second (age). We can to this with the plt.scatter() command. It expects at least two arguments: vectors of the same length, indicating the x and y coordinate of each point. In other words, we'll need to slice our data matrix into the first and second columns:

In [ ]:
x = data[:, 0]
y = data[:, 1]
plt.scatter(x, y);             # the semicolon stops jupyter from printing the result of the last function call

Let's make the dots a little smaller, and slightly transparent, to show the structure a little better. See [the documentation](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.scatter.html) for more options.

Let's also be good data scientists and label our axes.

In [ ]:
plt.scatter(x, y, s=3, alpha=0.2)
plt.xlabel('year of birth')
plt.ylabel('age');

The most prominent feature is the dense, diagonal line at the left. Can you explain why this is there?

In the middle of the plot, we see two, more noisy, more vague diagonal lines. Can you guess what they represent?

To clear this up, we can make a different plot: we can plot the year that the cricketer _died_ against their age. This value isn't given in the data, but it's easy to compute: we just sum their age with their year of birth. Numpy makes this expecially easy by overloading the basic operators like +, -, \* and /. These are all **element-wise** operators: if we sum two matrices of the same shape, the result will be a matrix (of that shape also), in which each element is the sum of the corresponding elements in the input matrices. 

In other words, to get the year of death, we can simply do:

In [ ]:
year_of_death = data[:,0] + data[:,1]

Let's check the distribution first, by plotting a histogram:

In [ ]:
plt.hist(year_of_death);

The big bar on the right is not some huge calamity in the cricket world. I just shows the large proportion of cricketers that were still alive when the data was gathered. Let's zoom in a little, and use some more bins to show the finer detail. Again, [the documentation](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.hist.html) shows you more options.

In [ ]:
plt.hist(year_of_death, bins=100, range=[1870, 1970]);

We see a pretty big spike for World War I, but World War II is hidden in the noise. If we return to the scatter plot, se can make it stand out a little more.

In [ ]:
plt.scatter(data[:,0]+data[:,1], data[:,1], s=3, alpha=0.2)
plt.xlabel('year of death')
plt.ylabel('age at death');

If you want to save your plot to a file, you can use ``plt.savefig('myplot.pdf')``. The filetype is automatically detected from the extension.

## Quick numpy tricks

You should now have a basic idea of how numpy works, and how to make simple plots. 
Numpy is a complex library with many options. We'll finish up by showing you a few important aspects, and pointing you  to some more elaborate tutorials.

### Matrix multplication

First up: matrix multiplication. For two matrices ``a`` and ``b``, ``a * b`` gives you an element-wise multiplication. What if you want to do a full matrix multiplication? That works like this:

In [ ]:
a = np.asarray([[1, 2],[3, 4]])
print(a)
b = np.eye(2) # the 2x2 identity matrix

print('\nelement-wise\n', a * b)

print('\nmatrix multiplication\n', a.dot(b))

### Broadcasting

[Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) is one of numpy's most complex, and most useful behaviors. Put simply, when you try apply an element-wise operation (like +) to two matrices that don't have the same size, numpy checks if it can stretch one of them to make the sizes match. 

The simplest example is combining a matrix with a scalar. Let's say we want to add 10 to every element in a matrix. 


In [ ]:
a + 10

Under the hood, numpy dynamically stretches  the scalar 10 our to a matrix of 2x2, filled with 10's and then adds that, element-wise, to ``a``.

Here is another example, adding a length 3 vector to a 16x3 matrix:

In [ ]:
a = np.random.rand(16,3)
b = np.asarray([0,1,2])
a + b

If the two matrices being added don't have the same number of dimensions, they are aligned from the last dimension. In this case, broadcasting was allowed, because the last dimension of ``a`` matched the last dimension of ``b``. If ``b`` had been 16 elements long, we would not be allowed to broadcast (try it).

In this case, we could add a dimension, to make ``b`` a 16x1 matrix. The broadcasting rules allow any dimension of size 1 to be stretched to match the other matrix.

I'm sure that right now, broadcasting seems quite mysterious. It's enough to be aware that this behavior exists. If you encounter it in action, you'll see how much easier and intuitive it can make things. The numpy documentation provides [a more complete explanation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) if you need one.

## Final comments

That's it for this worksheet. This doesn't make your numpy/matplotlib experts, but it hopefully gives you an indication of how things work, and a safe environment to experiment in. Just click the plus-icon in the toolbar make a new cell, and start playing around with the data.

To learn more about **numpy**, you can start here:
* [The official numpy quickstart guide](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [A more in-depth tutorial, with in-browser samples](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)
* [A very good walk through the most important functions and features](http://cs231n.github.io/python-numpy-tutorial/). From the famous [CS231n course](http://cs231n.github.io/), from Stanford.

To dive deeper into **matplotlib**, these are some good jumping-off points:
* [The official pyplot tutorial](https://matplotlib.org/users/pyplot_tutorial.html). Note that pyplot can accept basic python lists as well as numpy data.
* [A gallery of example MPL plots](https://matplotlib.org/gallery.html). Most of these do not use the pyplot state-machine interface, but the more low level objects like [Axes](https://matplotlib.org/api/axes_api.html).
* [In-depth walk through the main features and plot types](http://www.scipy-lectures.org/intro/matplotlib/matplotlib.html)

In the next worksheet, we'll see how to take some numpy data, and apply a machine learning algorithm to it, using the **sklearn** library.