In [1]:
import numpy as np
#VECTOR
vector=np.array([0,1,2,3,4,5,6,7])
print(vector.shape)
#MATRIZ
matriz=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz.shape)
#TENSOR
tensor=np.array([
    [[1,2,3], [4,5,6]],
    [[10,20,30], [40,55,60]],
    [[100,200,200], [49,59,69]]
])
print(tensor.shape)

(8,)
(3, 3)
(3, 2, 3)


In [6]:
#TRANSPUESTA
vector_t = vector.T
print(vector_t)
print(vector_t.shape)

[0 1 2 3 4 5 6 7]
(8,)


In [7]:
matriz_t = matriz.T
print(matriz)
print(matriz_t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print(tensor.shape)
print(tensor)
tensor_t=tensor.T
print(tensor_t.shape)
print(tensor_t)

(3, 2, 3)
[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  55  60]]

 [[100 200 200]
  [ 49  59  69]]]
(3, 2, 3)
[[[  1  10 100]
  [  4  40  49]]

 [[  2  20 200]
  [  5  55  59]]

 [[  3  30 200]
  [  6  60  69]]]


In [ ]:
#transpuesta de una transpuesta
tensor_t_t=tensor_t.T
print(tensor_t_t)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  55  60]]

 [[100 200 200]
  [ 49  59  69]]]


In [8]:
#suma de matrices dimensiones iguales
a=np.array([[1,1,1], [1,1,1]])
b=np.array([[2,2,2], [2,2,2]])
c=a+b
print(c)

[[3 3 3]
 [3 3 3]]


In [9]:
d=10+a
print(d)

[[11 11 11]
 [11 11 11]]


In [10]:
#SUMA DE MATRICES Y VECTORES BROADCASTING
#la ultima dimension debe coincidir con la primera
vector_ones=np.array([1,1,1,1,1])
matriz=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(vector_ones.shape)
print(matriz.shape)
print(matriz.T+vector_ones)

(5,)
(5, 4)
[[2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [11]:
print(matriz.T+vector_ones)


[[2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [2]:
#PRODUCTO INTERNO ENTRE UNA MATRIZ Y UN VERCTOR
a=np.array([[1,2],[2,2],[3,3]])
b=np.array([1,2,3])
print(a.T)

[[1 2 3]
 [2 2 3]]


In [3]:
a.T*b


array([[1, 4, 9],
       [2, 4, 9]])

In [ ]:
a.T.dot(b)

array([14, 15])

In [ ]:
x=np.array([[1,2,3],[3,2,1]])
y=np.array([[1,2,3],[3,2,1],[3,1,8]])
print(x.dot(y))

[[16  9 29]
 [12 11 19]]
